baseurl = "/"
languageCode = "en-us"
title = "Homepage"

paginage = 10
paginatePath ="casestudies"

enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = '<img src="/img/common/Visyond Logo Vector 2022.svg" alt="Logo">'
    url = "/"
  [[menu.main]]
    identifier = "solutions"
    name = "Solutions"
    url = "/solutions/"
  [[menu.main]]
    identifier = "test"
    name = "Solutions"
    url = "/solutions/"
    parent = "solutions"
  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/features/"
  [[menu.main]]
    identifier = "casestudy"
    name = "Case Studies"
    url = "/casestudy/"
  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing/"
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
